export const FX_LABELS = {
  0: "Hall Reverb",
  1: "Ambience",
  2: "Rich Plate Reverb",
  3: "Room Reverb",
  4: "Chamber Reverb",
  5: "Plate Reverb",
  6: "Vintage Reverb",
  7: "Vintage Room",
  8: "Gated Reverb",
  9: "Reverse Reverb",
  10: "Stereo Delay",
  11: "3-Tap Delay",
  12: "Rhythm Delay",
  13: "Stereo Chorus",
  14: "Stereo Flanger",
  15: "Stereo Phaser",
  16: "Dimensional Chorus",
  17: "Mood Filter",
  18: "Rotary Speaker",
  19: "Tremolo / Panner",
  20: "Suboctaver",
  21: "Delay + Chamber",
  22: "Chorus + Chamber",
  23: "Flanger + Chamber",
  24: "Delay + Chorus",
  25: "Delay + Flanger",
  26: "Modulation Delay",
  27: "Dual Graphic EQ",
  28: "Stereo Graphic EQ",
  29: "Dual TruEQ",
  30: "Stereo TruEQ",
  31: "Dual DeEsser",
  32: "Stereo DeEsser",
  33: "Stereo Xtec EQ1",
  34: "Dual Xtec EQ1",
  35: "Stereo Xtec EQ5",
  36: "Dual Xtec EQ5",
  37: "Wave Designer",
  38: "Precision Limiter",
  39: "Stereo Combinator",
  40: "Dual Combinator",
  41: "Stereo Fair Compressor",
  42: "M/S Fair Compressor",
  43: "Dual Fair Compressor",
  44: "Stereo Leisure Compressor",
  45: "Dual Leisure Compressor",
  46: "Stereo Ultimo Compressor",
  47: "Dual Ultimo Compressor",
  48: "Dual Enhancer",
  49: "Stereo Enhancer",
  50: "Dual Exciter",
  51: "Stereo Exciter",
  52: "Stereo Imager",
  53: "Edison Ex1",
  54: "Sound Maxer",
  55: "Dual Guitar Amp",
  56: "Stereo Guitar Amp",
  57: "Dual Tube Stage",
  58: "Stereo Tube Stage",
  59: "Dual Pitch Shifter",
  60: "Stereo Shifter",
}

export enum FX_1_4 {
  "HallReverb" = 0,
  "Ambience" = 1,
  "RichPlateReverb" = 2,
  "RoomReverb" = 3,
  "ChamberReverb" = 4,
  "PlateReverb" = 5,
  "VintageReverb" = 6,
  "VintageRoom" = 7,
  "GatedReverb" = 8,
  "ReverseReverb" = 9,
  "StereoDelay" = 10,
  "3TapDelay" = 11,
  "RhythmDelay" = 12,
  "StereoChorus" = 13,
  "StereoFlanger" = 14,
  "StereoPhaser" = 15,
  "DimensionalChorus" = 16,
  "MoodFilter" = 17,
  "RotarySpeaker" = 18,
  "Tremolo/Panner" = 19,
  "Suboctaver" = 20,
  "DelayAndChamber" = 21,
  "ChorusAndChamber" = 22,
  "FlangerAndChamber" = 23,
  "DelayAndChorus" = 24,
  "DelayAndFlanger" = 25,
  "ModulationDelay" = 26,
  "DualGraphicEQ" = 27,
  "StereoGraphicEQ" = 28,
  "DualTruEQ" = 29,
  "StereoTruEQ" = 30,
  "DualDeEsser" = 31,
  "StereoDeEsser" = 32,
  "StereoXtecEQ1" = 33,
  "DualXtecEQ1" = 34,
  "StereoXtecEQ5" = 35,
  "DualXtecEQ5" = 36,
  "WaveDesigner" = 37,
  "PrecisionLimiter" = 38,
  "StereoCombinator" = 39,
  "DualCombinator" = 40,
  "StereoFairCompressor" = 41,
  "M/SFairCompressor" = 42,
  "DualFairCompressor" = 43,
  "StereoLeisureCompressor" = 44,
  "DualLeisureCompressor" = 45,
  "StereoUltimoCompressor" = 46,
  "DualUltimoCompressor" = 47,
  "DualEnhancer" = 48,
  "StereoEnhancer" = 49,
  "DualExciter" = 50,
  "StereoExciter" = 51,
  "StereoImager" = 52,
  "EdisonEx1" = 53,
  "SoundMaxer" = 54,
  "DualGuitarAmp" = 55,
  "StereoGuitarAmp" = 56,
  "DualTubeStage" = 57,
  "StereoTubeStage" = 58,
  "DualPitchShifter" = 59,
  "StereoShifter" = 60,
}

export type FxType1To4 = (typeof FX_1_4)[keyof typeof FX_1_4]

export enum FX_5_8 {
  "StereoPhaser" = 15,
  "MoodFilter" = 17,
  "Tremolo/Panner" = 19,
  "Suboctaver" = 20,
  "DualGraphicEQ" = 27,
  "StereoGraphicEQ" = 28,
  "DualTruEQ" = 29,
  "StereoTruEQ" = 30,
  "DualDeEsser" = 31,
  "StereoDeEsser" = 32,
  "StereoXtecEQ1" = 33,
  "DualXtecEQ1" = 34,
  "StereoXtecEQ5" = 35,
  "DualXtecEQ5" = 36,
  "WaveDesigner" = 37,
  "PrecisionLimiter" = 38,
  "StereoFairCompressor" = 41,
  "M/SFairCompressor" = 42,
  "DualFairCompressor" = 43,
  "StereoLeisureCompressor" = 44,
  "DualLeisureCompressor" = 45,
  "StereoUltimoCompressor" = 46,
  "DualUltimoCompressor" = 47,
  "DualEnhancer" = 48,
  "StereoEnhancer" = 49,
  "DualExciter" = 50,
  "StereoExciter" = 51,
  "StereoImager" = 52,
  "EdisonEx1" = 53,
  "SoundMaxer" = 54,
  "DualGuitarAmp" = 55,
  "StereoGuitarAmp" = 56,
  "DualTubeStage" = 57,
  "StereoTubeStage" = 58,
}

export type FxType5To8 = (typeof FX_5_8)[keyof typeof FX_5_8]
