export const FX_LABELS_5_8 = [
  "Dual Graphic EQ",
  "Stereo Graphic EQ",
  "Dual TruEQ",
  "Stereo TruEQ",
  "Dual DeEsser",
  "Stereo DeEsser",
  "Stereo Xtec EQ1",
  "Dual Xtec EQ1",
  "Stereo Xtec EQ5",
  "Dual Xtec EQ5",
  "Wave Designer",
  "Precision Limiter",
  "Stereo Fair Compressor",
  "M/S Fair Compressor",
  "Dual Fair Compressor",
  "Stereo Leisure Compressor",
  "Dual Leisure Compressor",
  "Stereo Ultimo Compressor",
  "Dual Ultimo Compressor",
  "Dual Enhancer",
  "Stereo Enhancer",
  "Dual Exciter",
  "Stereo Exciter",
  "Stereo Imager",
  "Edison Ex1",
  "Sound Maxer",
  "Dual Guitar Amp",
  "Stereo Guitar Amp",
  "Dual Tube Stage",
  "Stereo Tube Stage",
  "Stereo Phaser",
  "Mood Filter",
  "Tremolo / Panner",
  "Suboctaver",
]

export const FX_LABELS_1_4 = [
  "Hall Reverb",
  "Ambience",
  "Rich Plate Reverb",
  "Room Reverb",
  "Chamber Reverb",
  "Plate Reverb",
  "Vintage Reverb",
  "Vintage Room",
  "Gated Reverb",
  "Reverse Reverb",
  "Stereo Delay",
  "3-Tap Delay",
  "Rhythm Delay",
  "Stereo Chorus",
  "Stereo Flanger",
  "Stereo Phaser",
  "Dimensional Chorus",
  "Mood Filter",
  "Rotary Speaker",
  "Tremolo / Panner",
  "Suboctaver",
  "Delay + Chamber",
  "Chorus + Chamber",
  "Flanger + Chamber",
  "Delay + Chorus",
  "Delay + Flanger",
  "Modulation Delay",
  "Dual Graphic EQ",
  "Stereo Graphic EQ",
  "Dual TruEQ",
  "Stereo TruEQ",
  "Dual DeEsser",
  "Stereo DeEsser",
  "Stereo Xtec EQ1",
  "Dual Xtec EQ1",
  "Stereo Xtec EQ5",
  "Dual Xtec EQ5",
  "Wave Designer",
  "Precision Limiter",
  "Stereo Combinator",
  "Dual Combinator",
  "Stereo Fair Compressor",
  "M/S Fair Compressor",
  "Dual Fair Compressor",
  "Stereo Leisure Compressor",
  "Dual Leisure Compressor",
  "Stereo Ultimo Compressor",
  "Dual Ultimo Compressor",
  "Dual Enhancer",
  "Stereo Enhancer",
  "Dual Exciter",
  "Stereo Exciter",
  "Stereo Imager",
  "Edison Ex1",
  "Sound Maxer",
  "Dual Guitar Amp",
  "Stereo Guitar Amp",
  "Dual Tube Stage",
  "Stereo Tube Stage",
  "Dual Pitch Shifter",
  "Stereo Shifter",
]

export type FX_LABELS_5_8_TYPE = typeof FX_LABELS_5_8[number]
export type FX_LABELS_1_4_TYPE = typeof FX_LABELS_1_4[number]
export type FX_LABEL = { label: FX_LABELS_5_8_TYPE | FX_LABELS_1_4_TYPE, value: number }

// The actual fx unit on the X32
export type FX_UNIT_NUMBER = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8

export const FX_LABELS_1_4_OPTIONS: FX_LABEL[] = FX_LABELS_1_4.map((value, index) => {
  return { label: value, value: index }
})


export const FX_LABELS_5_8_OPTIONS: FX_LABEL[] = FX_LABELS_5_8.map((value, index) => {
  return { label: value, value: index }
})


export function fxLabelsToOptions (labels: (FX_LABELS_5_8_TYPE | FX_LABELS_1_4_TYPE)[]): FX_LABEL[] {
  return labels.map((value, index) => {
    return { label: value, value: index }
  })
}

// export enum FX_1_4 {
//   "HallReverb" = 0,
//   "Ambience" = 1,
//   "RichPlateReverb" = 2,
//   "RoomReverb" = 3,
//   "ChamberReverb" = 4,
//   "PlateReverb" = 5,
//   "VintageReverb" = 6,
//   "VintageRoom" = 7,
//   "GatedReverb" = 8,
//   "ReverseReverb" = 9,
//   "StereoDelay" = 10,
//   "3TapDelay" = 11,
//   "RhythmDelay" = 12,
//   "StereoChorus" = 13,
//   "StereoFlanger" = 14,
//   "StereoPhaser" = 15,
//   "DimensionalChorus" = 16,
//   "MoodFilter" = 17,
//   "RotarySpeaker" = 18,
//   "Tremolo/Panner" = 19,
//   "Suboctaver" = 20,
//   "DelayAndChamber" = 21,
//   "ChorusAndChamber" = 22,
//   "FlangerAndChamber" = 23,
//   "DelayAndChorus" = 24,
//   "DelayAndFlanger" = 25,
//   "ModulationDelay" = 26,
//   "DualGraphicEQ" = 27,
//   "StereoGraphicEQ" = 28,
//   "DualTruEQ" = 29,
//   "StereoTruEQ" = 30,
//   "DualDeEsser" = 31,
//   "StereoDeEsser" = 32,
//   "StereoXtecEQ1" = 33,
//   "DualXtecEQ1" = 34,
//   "StereoXtecEQ5" = 35,
//   "DualXtecEQ5" = 36,
//   "WaveDesigner" = 37,
//   "PrecisionLimiter" = 38,
//   "StereoCombinator" = 39,
//   "DualCombinator" = 40,
//   "StereoFairCompressor" = 41,
//   "M/SFairCompressor" = 42,
//   "DualFairCompressor" = 43,
//   "StereoLeisureCompressor" = 44,
//   "DualLeisureCompressor" = 45,
//   "StereoUltimoCompressor" = 46,
//   "DualUltimoCompressor" = 47,
//   "DualEnhancer" = 48,
//   "StereoEnhancer" = 49,
//   "DualExciter" = 50,
//   "StereoExciter" = 51,
//   "StereoImager" = 52,
//   "EdisonEx1" = 53,
//   "SoundMaxer" = 54,
//   "DualGuitarAmp" = 55,
//   "StereoGuitarAmp" = 56,
//   "DualTubeStage" = 57,
//   "StereoTubeStage" = 58,
//   "DualPitchShifter" = 59,
//   "StereoShifter" = 60,
// }

// export type FxType1To4 = (typeof FX_1_4)[keyof typeof FX_1_4]

// export enum FX_5_8 {
//   "StereoPhaser" = 15,
//   "MoodFilter" = 17,
//   "Tremolo/Panner" = 19,
//   "Suboctaver" = 20,
//   "DualGraphicEQ" = 27,
//   "StereoGraphicEQ" = 28,
//   "DualTruEQ" = 29,
//   "StereoTruEQ" = 30,
//   "DualDeEsser" = 31,
//   "StereoDeEsser" = 32,
//   "StereoXtecEQ1" = 33,
//   "DualXtecEQ1" = 34,
//   "StereoXtecEQ5" = 35,
//   "DualXtecEQ5" = 36,
//   "WaveDesigner" = 37,
//   "PrecisionLimiter" = 38,
//   "StereoFairCompressor" = 41,
//   "M/SFairCompressor" = 42,
//   "DualFairCompressor" = 43,
//   "StereoLeisureCompressor" = 44,
//   "DualLeisureCompressor" = 45,
//   "StereoUltimoCompressor" = 46,
//   "DualUltimoCompressor" = 47,
//   "DualEnhancer" = 48,
//   "StereoEnhancer" = 49,
//   "DualExciter" = 50,
//   "StereoExciter" = 51,
//   "StereoImager" = 52,
//   "EdisonEx1" = 53,
//   "SoundMaxer" = 54,
//   "DualGuitarAmp" = 55,
//   "StereoGuitarAmp" = 56,
//   "DualTubeStage" = 57,
//   "StereoTubeStage" = 58,
// }

// export type FxType5To8 = (typeof FX_5_8)[keyof typeof FX_5_8]
